#if !canImport(ObjectiveC)
import XCTest

extension DeviceInfoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeviceInfoTests = [
        ("testCurrentDeviceInfo", testCurrentDeviceInfo),
        ("testSwiftUIEnvironment", testSwiftUIEnvironment),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DeviceInfoTests.__allTests__DeviceInfoTests),
    ]
}
#endif
